---
- name: Start Rancher Worker
  docker_container:
    name: rancher-worker
    image: rancher/server:{{rancherWorkerTag}}
    restart_policy: unless-stopped
    volumes:
      - "{{rancherWorkerDataDir}}:/var/lib/mysql"
    ports:
    - "{{rancherClientPort}}:8080"
  become: true