---
- name: Install httpd.
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - httpd
  become: true
  
- name: Ensures that itoa yum repo dir exists.
  file: 
    path: '{{ repoDirYum }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0777
  become: true

- name: Ensures that itoa webdav repo dir exists.
  file: 
    path: '{{ repoDirWebdav }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0777
  become: true

- name: Install createrepo if its not already installed.
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - createrepo
  become: true

- name: create a rpm repo. 
  command: createrepo '{{ repoDirYum }}'

- name: enable httpd auto start on reboot
  systemd:
    name: httpd
    enabled: yes
    masked: no
  become: true

- name: reload service httpd, in all cases
  systemd:
    name: httpd
    state: restarted
  become: true