---
- hosts: master
  tasks:

  - name: proxy bb diretorio
    file: path=/etc/systemd/system/docker.service.d state=directory
    become: true

  - name: Copy http-proxy.conf Docker Master Proxy
    copy:
      src: files/http-proxy.conf
      dest: /etc/systemd/system/docker.service.d/http-proxy.conf
#    state: present
    become: true

  - name: Copy https-proxy.conf - Docker Master Proxy
    copy:
      src: files/https-proxy.conf
      dest: /etc/systemd/system/docker.service.d/https-proxy.conf
    become: true

  - name: start docker-ce service
    systemd: name=docker state=started
    become: true

  - name: Start local Docker Registry
    docker_container:
      name: registry
      image: registry:2
      restart_policy: always
      volumes:
        - "/etc/docker/registry_config.yml:/etc/docker/registry/config.yml"
        - "/etc/docker/certs.d:/certs"
        - "/data/docker/registry:/var/lib/registry"
      ports:
      - "443:443"
    become: true

  - name: Start local Docker Mirror
    docker_container:
      name: mirror
      image: registry:2
      restart_policy: always
      volumes:
        - "/etc/docker/mirror_config.yml:/etc/docker/registry/config.yml"
        - "/etc/docker/certs.d:/certs"
        - "/data/docker/registry:/var/lib/registry"
      ports:
      - "5555:443"
    become: true

  - name: Start Rancher Server
    docker_container:
      name: rancher-server
      image: rancher/server:stable
      restart_policy: unless-stopped
      volumes:
        - "/data/docker/rancher/var/lib/mysql:/var/lib/mysql"
      ports:
      - "8080:8080"
    become: true

