---
- hosts: machine1


  tasks:
  
  - name: Include vars.
    include_vars:
      file: vars.yml
      name: var

  - name: Cria o usuario itoausr na maquina do repositorio.
    user:
      name: "{{ var.createuser }}"
      state: present
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    become: true

  - name: create self-signed ITOA SSL certs
    command: openssl req -newkey rsa:2048 -nodes -x509 -subj "/C=BR/ST=Distrito Federal/L=Brasilia/O=BB/CN=*.itoa.servicos.bb.com.br" -days 1825 -keyout /etc/ssl/certs/itoa.key -out /etc/ssl/certs/itoa.crt
    become: true

  - name: retrieve public key
    shell: cat /home/{{ var.createuser }}/.ssh/id_rsa.pub
    register: repo_public_key
    changed_when: false
    become: true


- hosts: all

  tasks:
  
  - name: Include vars.
    include_vars:
      file: vars.yml
      name: var
  - name:

    user:
      name: "{{ var.createuser }}"
      state: present
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    become: true


  - name: add itoa-repo public key to machines authorized_keys
    authorized_key:
      user: "{{ var.createuser }}"
      key: "{{ hostvars['machine1'].repo_public_key.stdout }}"
    become: true

