---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
    - docker-ce
  become: true

- name: Install Docker-ce from itoa yum repo.
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ dockerVersion }}'
  become: true