---
- name: Install PIP.
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python-pip
  become: true

- name: Install Docker Python Api for Ansible
  pip: name={{item}} state=present
  with_items:
    - docker-py
  state: present
  become: true  

- name: Update /etc/hosts to include registry, mirror, master
  lineinfile: dest=/etc/hosts line='{{ masterip }} {{ registryHost }} {{ mirrorHost }} {{ masterHost }}' state=present
  become: true

#- name: Update /etc/hosts from inventory
#  lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_eth1.ipv4.address}} {{item}}' state=present
#  with_items: '{{groups.all}}'
#  tags:
#    - hosts
#  become: true